### ISSUE TITLE
[BE] Sum by group to current user in `GET groups`

### ISSUE THREAD

**Issue by YevheniiStepaniuk** [Romm17/FriendTreasuryAPI#12]

**Comment by Romm17** [comment]
Hello, @YevheniiStepaniuk !
I've realized that functionality u required is already reaized.
get sum by group to user = GET /api/v1/payments/sum?group={groupID}&userTo={userToId}
any other queries?

**Comment by YevheniiStepaniuk** [comment]
@Romm17 
Not this, could you with `GET /api/v1/groups/my` return sum by each group for current user

**Comment by Romm17** [comment]
@YevheniiStepaniuk, ok, I got it. need some time to think :)

**Comment by Romm17** [comment]
@YevheniiStepaniuk ,
I think it is better not to mix 2 request (get groups and group payment sum), but rather do it separately
1) get all groups for user
2) asynchronously get sum for each group
how do u think?

**Comment by YevheniiStepaniuk** [comment]
@Romm17 I think it is not good because for example I have 1000 groups and I call 1000 times your server and it is for every user
