### ISSUE TITLE
[BE] 401

### ISSUE THREAD

**Issue by YevheniiStepaniuk** [Romm17/FriendTreasuryAPI#15]
When we trying to send a request without token, we got 400 `Missing request header '${ft.token.header}' for method parameter of type String`.
When we trying to send request with expired token, we got 500`An Authentication object was not found in the SecurityContext`

Please fix and return 401 for both req

**Comment by Romm17** [comment]
https://github.com/alvarosanchez/grails-spring-security-rest/issues/137
